# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63aa417998eea20f4f5a783a865e1224"
application_url = "https://swiss-blond-vacancies-spice.trycloudflare.com"
embedded = true
name = "growing-venture-app"
handle = "growing-venture-app-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://swiss-blond-vacancies-spice.trycloudflare.com/auth/callback",
  "https://swiss-blond-vacancies-spice.trycloudflare.com/auth/shopify/callback",
  "https://swiss-blond-vacancies-spice.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
